### ISSUE TITLE
How to patch deployment?

### ISSUE THREAD

**Issue by paymog** [ianbelcher/eks-kubectl-action#19]
I'm trying to patch a deployment with this action but having some trouble. 

Here's my action

```yaml
      - name: Change patch api-server deployment version (including pod template)
        uses: ianbelcher/eks-kubectl-action@master
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: graph-tools-api-server
          IMAGE_TAG: ${{ github.sha }}
          PATCH: "{\"metadata\":{\"labels\":{\"tags.datadoghq.com/version\":\"$IMAGE_TAG\"}},\"spec\":{\"template\":{\"metadata\":{\"labels\":{\"tags.datadoghq.com/version\":\"$IMAGE_TAG\"}}}}}"
        with:
          cluster_name: ${{ secrets.DEV_CLUSTER_NAME }}
          args: patch deployment goldsky-api --patch $PATCH
```

but when I run this I get the following output

```
/usr/bin/docker run --name ghcrioianbelcherekskubectlactionlatest_467327 --label 817f70 --workdir /github/workspace --rm -e "AWS_DEFAULT_REGION" -e "AWS_REGION" -e "AWS_ACCESS_KEY_ID" -e "AWS_SECRET_ACCESS_KEY" -e "ECR_REGISTRY" -e "ECR_REPOSITORY" -e "IMAGE_TAG" -e "PATCH" -e "INPUT_CLUSTER_NAME" -e "INPUT_ARGS" -e "INPUT_AWS_ACCESS_KEY_ID" -e "INPUT_AWS_SECRET_ACCESS_KEY" -e "INPUT_AWS_REGION" -e "INPUT_EKS_ROLE_ARN" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "RUNNER_DEBUG" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/goldsky/goldsky":"/github/workspace" ghcr.io/ianbelcher/eks-kubectl-action:latest patch deployment goldsky-api --patch $PATCH
aws version
aws-cli/1.22.26 Python/3.10.0a7 Linux/5.15.0-1019-azure botocore/1.23.26
Attempting to update kubeconfig for aws
Added new context arn:aws:eks:***:***:cluster/*** to /github/home/.kube/config
Error from server (BadRequest): json: cannot unmarshal string into Go value of type map[string]interface {}
```

If I run this locally in zsh, it seems to work well.

```shell
10:10AM /Users/paymahn/code/goldsky/graph-tools/packages/cli paymahn/update.api.server.k8s.dd.version.labels ✱
 ❯❯❯ export IMAGE_TAG=lol
10:10AM /Users/paymahn/code/goldsky/graph-tools/packages/cli paymahn/update.api.server.k8s.dd.version.labels ✱
 ❯❯❯ export PATCH="{\"metadata\":{\"labels\":{\"tags.datadoghq.com/version\":\"$IMAGE_TAG\"}},\"spec\":{\"template\":{\"metadata\":{\"labels\":{\"tags.datadoghq.com/version\":\"$IMAGE_TAG\"}}}}}"
10:10AM /Users/paymahn/code/goldsky/graph-tools/packages/cli paymahn/update.api.server.k8s.dd.version.labels ✱
 ❯❯❯ k patch deployment goldsky-api --patch $PATCH
deployment.apps/goldsky-api patched (no change)
```

**Comment by ianbelcher** [comment]
Hey @paymog,

You need to supply your AWS _ACCESS_KEY and AWS_SECRET_ACCESS_KEY in order for the action to authenticate and be authorized to make changes, it appears to be failing otherwise.

Let me know if you have any other issues once you've supplied these Paramus and I'll see what I can do to help you out.

**Comment by paymog** [comment]
Hey Ian, my mistake, I should have been more clear. I'm successfully connecting with the cluster, here's a more complete view of my action:

```
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          # This uses an IAM user. Definitiely could be more secure
          aws-access-key-id: ${{ secrets.DEV_IAM_GITHUB_ACTIONS_GENERAL_SECRET_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEV_IAM_GITHUB_ACTIONS_GENERAL_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Change patch api-server deployment version (including pod template)
        uses: ianbelcher/eks-kubectl-action@master
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: graph-tools-api-server
          IMAGE_TAG: ${{ github.sha }}
        with:
          cluster_name: ${{ secrets.DEV_CLUSTER_NAME }}
          args: patch deployment goldsky-api --patch '{"metadata":{"labels":{"tags.datadoghq.com/version":$IMAGE_TAG}},"spec":{"template":{"metadata":{"labels":{"tags.datadoghq.com/version":$IMAGE_TAG}}}}}'

      - name: Deploy goldsky-api to k8s
        uses: ianbelcher/eks-kubectl-action@master
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: graph-tools-api-server
        with:
          cluster_name: ${{ secrets.DEV_CLUSTER_NAME }}
          args: set image deployment/goldsky-api goldsky-api=${{ steps.login-ecr.outputs.registry }}/graph-tools-api-server:${{ github.sha }}
```

The first step connects to my AWS cluster using `aws-actions/configure-aws-credentials@v1`.

I'm adding a new step to perform the patch. The step named `Deploy goldsky-api to k8s` has been working successfully for a while but new step which performs the patching is failing.

**Comment by ianbelcher** [comment]
Cool cool, so I'm not sure that you are getting env interpolation in this case which means that the json would be incorrect which matches the error.

If you replace $IMAGE with ${{ github.sha }} for the arg param as a test, does this work?

**Comment by paymog** [comment]
ah yup that works! for completeness in case anyone else stumbles on this, here's the full step that worked for me:

```
      - name: Change patch api-server deployment version (including pod template)
        uses: ianbelcher/eks-kubectl-action@master
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: graph-tools-api-server
        with:
          cluster_name: ${{ secrets.DEV_CLUSTER_NAME }}
          # prettier-ignore
          args: patch deployment goldsky-api --patch "{\"metadata\":{\"labels\":{\"tags.datadoghq.com/version\":\"${{ github.sha }}\"}}}"
```
